# Cilium Helm Values
# https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium

k8sServiceHost: "172.31.7.100"
k8sServicePort: "6443"

kubeProxyReplacement: "strict"

bpf:
  masquerade: true

gatewayAPI:
  enabled: true

ipam:
  mode: "kubernetes"

operator:
  replicas: 1

serviceAccounts:
  cilium:
    create: true
  operator:
    create: true

hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
