apiVersion: v2
kind: Chart
metadata:
  name: prometheus-wrapper
  version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 51.2.0
    repository: https://prometheus-community.github.io/helm-charts
