apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared.yaml
  # This is a placeholder. In a real setup, you would include the Deployment and ConfigMap for the tunnel.
  # For now, we assume a basic manifest or Helm chart is used.
  # Since cloudflared doesn't have a standard "remote" kustomize base like cert-manager, 
  # we will create a local deployment.yaml for it.

components:
  - deployment.yaml
